services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "2000:80"
    env_file:
      - .env
    networks:
      - webnet

networks:
  webnet:
    driver: bridge